#!/bin/bash
# +--------------------------------------------------------------------+
# EFA Project update script 
# Version 20130127
# +--------------------------------------------------------------------+
# Copyright (C) 2012~2013  http://www.efa-project.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# +--------------------------------------------------------------------+

#----------------------------------------------------------------#
# Variables
#----------------------------------------------------------------#
VERSIONFILE="/etc/EFA-version"
CVERSION="`cat $VERSIONFILE`"
MIRROR1="http://www.efa-project.org"
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# Running updates
#----------------------------------------------------------------#
echo "[EFA] Your current version is $CVERSION"
if [[ $CVERSION = "EFA-0.2" ]]
	then
		cd /var/EFA/update
		wget -q $MIRROR1/update/0.3/update-efa-to-0.3.bash
		chmod 700 update-efa-to-0.3.bash
		/var/EFA/update/update-efa-to-0.3.bash
	elif [[ $CVERSION = "EFA-0.3" ]]
		then
			cd /var/EFA/update
			wget -q $MIRROR1/update/0.4/update-efa-to-0.4.bash
			chmod 700 update-efa-to-0.4.bash
			/var/EFA/update/update-efa-to-0.4.bash
	else
		echo "[EFA] ERROR no update file available for your EFA version"
fi